/**
 * Scenario World State V2 fixtures for Nordkern Foods and Nexora.
 * Location: shared/domain/world-fixtures.ts
 * Authoritative seed data only — no engine effects here.
 */
import type { WorldModules } from './types.ts'

/** Nordkern Foods — production / retail / capacity world seed. */
export function nordkernWorldV2(): WorldModules {
  return {
    customers: [
      {
        id: 'nk_cust_lidl',
        name: 'Lidl',
        lifecycle: 'active',
        visibility: 'player_visible',
        segment: 'discounter',
        revenueShareBps: 1900,
        contributionMarginBps: 750,
        contributionMarginVisibility: 'researchable',
      },
      {
        id: 'nk_cust_rewe',
        name: 'REWE',
        lifecycle: 'active',
        visibility: 'player_visible',
        segment: 'full_range',
        revenueShareBps: 1400,
        contributionMarginBps: 1100,
        contributionMarginVisibility: 'advisor_visible',
      },
      {
        id: 'nk_cust_foodservice',
        name: 'Foodservice Bundle',
        lifecycle: 'active',
        visibility: 'player_visible',
        segment: 'foodservice',
        revenueShareBps: 900,
      },
      {
        id: 'nk_cust_legacy_promo',
        name: 'Promo-Partner Ost',
        lifecycle: 'ended',
        visibility: 'player_visible',
        segment: 'promo',
        revenueShareBps: 0,
      },
    ],
    products: [
      {
        id: 'nk_prod_dairy_core',
        name: 'Kernmolkerei Standard',
        lifecycle: 'active',
        visibility: 'player_visible',
        category: 'dairy',
        annualRevenueCents: 6_200_000_000,
      },
      {
        id: 'nk_prod_premium_line',
        name: 'Nordkern Premium',
        lifecycle: 'active',
        visibility: 'player_visible',
        category: 'premium',
        annualRevenueCents: 3_100_000_000,
      },
      {
        id: 'nk_prod_private_label',
        name: 'Handelsmarke Volumen',
        lifecycle: 'active',
        visibility: 'player_visible',
        category: 'private_label',
        annualRevenueCents: 5_500_000_000,
      },
    ],
    departments: [
      {
        id: 'nk_dept_ops',
        name: 'Produktion',
        lifecycle: 'active',
        visibility: 'player_visible',
        headcount: 410,
        focus: 'Werke und Auslastung',
      },
      {
        id: 'nk_dept_sales',
        name: 'Vertrieb Handel',
        lifecycle: 'active',
        visibility: 'player_visible',
        headcount: 48,
        focus: 'Key Accounts und Promotions',
      },
      {
        id: 'nk_dept_hr',
        name: 'People & Works Council',
        lifecycle: 'active',
        visibility: 'advisor_visible',
        headcount: 22,
        focus: 'Schichtmodelle und Betriebsrat',
      },
    ],
    projects: [
      {
        id: 'nk_proj_thuringia_auto',
        name: 'Thüringen-Automatisierung',
        lifecycle: 'active',
        visibility: 'player_visible',
        budgetCents: 1_850_000_000,
        progressBps: 1200,
      },
      {
        id: 'nk_proj_debottleneck',
        name: 'Debottlenecking Linie 2',
        lifecycle: 'active',
        visibility: 'advisor_visible',
        budgetCents: 420_000_000,
        progressBps: 800,
      },
    ],
    keyPeople: [
      {
        id: 'nk_person_plant_th',
        name: 'Ines Vogel',
        lifecycle: 'active',
        visibility: 'player_visible',
        role: 'Werkleitung Thüringen',
        departmentId: 'nk_dept_ops',
        flightRiskBps: 3800,
        flightRiskVisibility: 'hidden',
      },
      {
        id: 'nk_person_sales_ka',
        name: 'Torben Meissner',
        lifecycle: 'active',
        visibility: 'player_visible',
        role: 'Key Account Lidl',
        departmentId: 'nk_dept_sales',
      },
    ],
    locations: [
      {
        id: 'nk_loc_thuringia',
        name: 'Werk Thüringen',
        lifecycle: 'active',
        visibility: 'player_visible',
        kind: 'plant',
        utilizationBps: 9400,
      },
      {
        id: 'nk_loc_lower_saxony',
        name: 'Werk Niedersachsen',
        lifecycle: 'active',
        visibility: 'player_visible',
        kind: 'plant',
        utilizationBps: 9000,
      },
      {
        id: 'nk_loc_brandenburg',
        name: 'Werk Brandenburg',
        lifecycle: 'active',
        visibility: 'player_visible',
        kind: 'plant',
        utilizationBps: 8900,
      },
      {
        id: 'nk_loc_hq',
        name: 'Zentrale Hamburg',
        lifecycle: 'active',
        visibility: 'player_visible',
        kind: 'office',
        utilizationBps: 7200,
      },
    ],
    contracts: [
      {
        id: 'nk_contract_lidl_annual',
        name: 'Lidl Jahreskontrakt',
        lifecycle: 'active',
        visibility: 'player_visible',
        counterpartyId: 'nk_cust_lidl',
        renewalDay: 180,
        annualValueCents: 2_812_000_000,
      },
      {
        id: 'nk_contract_energy_hedge',
        name: 'Energie-Hedge 24/25',
        lifecycle: 'active',
        visibility: 'researchable',
        counterpartyId: 'nk_sys_energy',
        renewalDay: 90,
        annualValueCents: 310_000_000,
      },
    ],
    competitors: [
      {
        id: 'nk_comp_milchkraft',
        name: 'Milchkraft AG',
        lifecycle: 'active',
        visibility: 'player_visible',
        segmentFocus: 'Handelsmarke Discounter',
        threatBps: 6200,
        threatVisibility: 'hidden',
      },
      {
        id: 'nk_comp_alpine',
        name: 'Alpine Fresh',
        lifecycle: 'active',
        visibility: 'advisor_visible',
        segmentFocus: 'Premium Molkerei',
        threatBps: 4100,
        threatVisibility: 'advisor_visible',
      },
    ],
  }
}

/** Nexora — SaaS growth / enterprise / platform world seed. */
export function nexoraWorldV2(): WorldModules {
  return {
    customers: [
      {
        id: 'nx_cust_translog',
        name: 'TransLog',
        lifecycle: 'active',
        visibility: 'player_visible',
        segment: 'enterprise',
        revenueShareBps: 1800,
        contributionMarginBps: 4200,
        contributionMarginVisibility: 'advisor_visible',
      },
      {
        id: 'nx_cust_mid_market_pool',
        name: 'Mid-Market Cohort',
        lifecycle: 'active',
        visibility: 'player_visible',
        segment: 'mid_market',
        revenueShareBps: 5200,
      },
      {
        id: 'nx_cust_churned_fleet',
        name: 'FleetOne (churned)',
        lifecycle: 'cancelled',
        visibility: 'player_visible',
        segment: 'mid_market',
        revenueShareBps: 0,
      },
    ],
    products: [
      {
        id: 'nx_prod_dispatch_core',
        name: 'Nexora Dispatch Core',
        lifecycle: 'active',
        visibility: 'player_visible',
        category: 'saas_core',
        annualRevenueCents: 980_000_000,
      },
      {
        id: 'nx_prod_ai_dispatch',
        name: 'AI Dispatch (beta)',
        lifecycle: 'active',
        visibility: 'player_visible',
        category: 'ai_addon',
        annualRevenueCents: 80_000_000,
      },
      {
        id: 'nx_prod_translog_fork',
        name: 'TransLog Custom Routing',
        lifecycle: 'active',
        visibility: 'advisor_visible',
        category: 'custom',
        annualRevenueCents: 120_000_000,
      },
    ],
    departments: [
      {
        id: 'nx_dept_eng',
        name: 'Engineering',
        lifecycle: 'active',
        visibility: 'player_visible',
        headcount: 32,
        focus: 'Platform und Integrationen',
      },
      {
        id: 'nx_dept_sales',
        name: 'Sales',
        lifecycle: 'active',
        visibility: 'player_visible',
        headcount: 18,
        focus: 'Enterprise und Mid-Market',
      },
      {
        id: 'nx_dept_cs',
        name: 'Customer Success',
        lifecycle: 'active',
        visibility: 'player_visible',
        headcount: 12,
        focus: 'Renewals und Adoption',
      },
    ],
    projects: [
      {
        id: 'nx_proj_ai_platform',
        name: 'Generische AI-Dispatch-Plattform',
        lifecycle: 'active',
        visibility: 'player_visible',
        budgetCents: 55_000_000,
        progressBps: 1500,
      },
      {
        id: 'nx_proj_translog_renewal',
        name: 'TransLog Renewal Delivery',
        lifecycle: 'active',
        visibility: 'player_visible',
        budgetCents: 40_000_000,
        progressBps: 2800,
      },
    ],
    keyPeople: [
      {
        id: 'nx_person_cto',
        name: 'Jonas Berg',
        lifecycle: 'active',
        visibility: 'player_visible',
        role: 'CTO',
        departmentId: 'nx_dept_eng',
      },
      {
        id: 'nx_person_vp_eng',
        name: 'Ayla Demir',
        lifecycle: 'active',
        visibility: 'advisor_visible',
        role: 'VP Engineering (interim)',
        departmentId: 'nx_dept_eng',
        flightRiskBps: 5500,
        flightRiskVisibility: 'researchable',
      },
    ],
    locations: [
      {
        id: 'nx_loc_berlin',
        name: 'HQ Berlin',
        lifecycle: 'active',
        visibility: 'player_visible',
        kind: 'office',
        utilizationBps: 7800,
      },
      {
        id: 'nx_loc_munich',
        name: 'Sales Hub München',
        lifecycle: 'active',
        visibility: 'player_visible',
        kind: 'office',
        utilizationBps: 6400,
      },
    ],
    contracts: [
      {
        id: 'nx_contract_translog',
        name: 'TransLog MSA + Renewal',
        lifecycle: 'active',
        visibility: 'player_visible',
        counterpartyId: 'nx_cust_translog',
        renewalDay: 210,
        annualValueCents: 210_000_000,
      },
      {
        id: 'nx_contract_cloud_commit',
        name: 'Cloud Commit (infra)',
        lifecycle: 'active',
        visibility: 'hidden',
        counterpartyId: 'nx_sys_cloud',
        renewalDay: 120,
        annualValueCents: 48_000_000,
      },
    ],
    competitors: [
      {
        id: 'nx_comp_routely',
        name: 'Routely',
        lifecycle: 'active',
        visibility: 'player_visible',
        segmentFocus: 'Mid-Market AI Dispatch',
        threatBps: 7100,
        threatVisibility: 'researchable',
      },
      {
        id: 'nx_comp_logix',
        name: 'LogiX Enterprise',
        lifecycle: 'active',
        visibility: 'advisor_visible',
        segmentFocus: 'Enterprise TMS',
        threatBps: 4800,
        threatVisibility: 'advisor_visible',
      },
    ],
  }
}
